### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by clincl** [UB-CSE/course-project-a9-collegehub#15]

**Comment by clincl** [comment]
Link
<Summary> (Bullet Points)

**Comment by Sauptik07** [comment]
**Link for step by step automation using selenium :** https://www.youtube.com/watch?v=FFDDN1C1MEQ 
(Jump to 14:03) 
**Documentation of Selenium** - https://www.selenium.dev/documentation/en/getting_started/quick/
This will be helpful to revisit to catch up on some fundamental concepts/syntax


**Imports**
- import webdriver from selenium 
- import time
- import keys from webdriver 

**Steps**
- set page load timeout 
- go to the desired website. For example (google.com)
- Access element by name and id, followed by an input. For example, 'how to cook food' in the search bar of google. 
- Use any of the selenium features, for example .click() to check a button like 'google search'
- Instruct the wait time with sleep
- Finally quit

**Note**
For third party drivers: Go to seleniumHQ.com to download extensions, for example Chrome.exe
Test for multiple drivers. 


**Python and Django debugging**
Link - https://code.visualstudio.com/docs/python/tutorial-django
Being new to Django, I believe debugging is an important aspect to be comfortable with to reduce bug tracking time.

**Comment by cjperez2017** [comment]
**Learned how Django's unit test work and did a demo**: https://docs.djangoproject.com/en/3.1/topics/testing/overview/

- Tests create a new test database so it doesn't interfere with existing data
- Tests are done with a tests.py file in the app folder
- run with 'python3 manage.py test'
- All test should be a class which inherent a TestCase
- Within the test class create a method setUp(self) to initialize before the test
- Within the test class create a methods that stat with 'test' otherwise the test will be ignore (ex: 'test_default', Note: helper functions should not start with 'test')


**Learned how domains and subdomains work**: https://www.hostgator.com/blog/subdomain-vs-domain/

- Need to purchase a domain first
- Then you can split a subdomain off the domain
- The subdomain can then be accessed by <subdomain>.<domain> or <domain>/<subdomain>

**A way to create subdomains with heroku**: https://devcenter.heroku.com/articles/custom-domains

Note: Using subdomains would be a great way to give users their own portfolio site based on ours

**Comment by MayankJ99** [comment]
**A Basic SEO for Django**  
https://www.vinta.com.br/blog/2015/basic-seo-django/
https://medium.com/@bedjango/4-seo-tips-to-position-your-website-using-django-96999d373222

- Include Meta tags
- Include Cache-control
- Include sitemap
- Use post save signals to handle slug/URL changes in your models

**Comment by tamaghan** [comment]
**Links for Frontend frameworks for basic use:**

- **Bootstrap4**
_https://getbootstrap.com_
We will use Bootstrap for basic buttons and cards throughout the website.
- **Jquery**
_https://api.jquery.com_
For basic HTML5 work.
- **ColorHunt**
_https://colorhunt.co/palettes/popular_
Different templates will have different themes and this is where colorhunt will help us pick and choose color combinations for the right template.
- **Freebiesupply**
_https://freebiesupply.com_ 
To get help in some design concepts for different backgrounds of templates.
- **ScreenTests for HTML**
_http://whatismyscreenresolution.net_
This link will help us test the functionality of the website on all types of machines without testing it physically on a different screen.
- **Figma**
_https://www.figma.com_
Figma helps create freehand drawing and texts which then can be converted into plain CSS or SVG. We will use this to create our product logo.
- **Animate**
_https://animate.style_
Open-source GitHub code to animate texts and cards throughout the website.

**Comment by rayanray** [comment]
**Testing for a Django web application:**
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing?fbclid=IwAR0d__XHEUgwJgkaFe8j0LnSuY1CaMb8ARJfAr5neFz8ap3rBTea7m-k6hw

**Database testing using Selenium Webdriver:**
https://www.softwaretestinghelp.com/database-testing-using-selenium-webdriver-selenium-tutorial-28/amp/?fbclid=IwAR03XY7hO6waSJKySzPzZVy_Uhs-S0PGat4bExE9ANSMI8aAKvE6Hc8d--w

**Starters guide for backend testing**
https://www.softwaretestinghelp.com/how-to-perform-backend-testing/

**Tool for complete software testing** 
https://smartbear.com/
